apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: storefinder-indexer-build
spec:
  timeout: 20m
  serviceAccountName: svc-build
  source:    
    git:
      url: https://github.com/storefinder/indexer.git
      revision: master
  template:
    name: ci-build-template
    arguments:
    - name: IMAGE
      value: gcr.io/$PROJECT_ID/storefinder/indexer:latest